### ISSUE TITLE
Allow to specify AWS VPC subnet id

### ISSUE THREAD

**Issue by pditommaso** [kubenow/KubeNow#100]
Is there a way to provide an existing VPC subnet id when setting up the cluster ?

**Comment by andersla** [comment]
I think this can easily be an option now when we are moving to Terraform 0.8 (Terraform 0.8 has conditionals)
For now you would need to modify the file aws/main.tf:

comment out: 
```
# VPC Virtual Private Cloud - Networking
module "vpc" {
  source = "./vpc"
  name_prefix = "${var.cluster_prefix}"
  availability_zone = "${var.availability_zone}" 
}
```
and then insert your existing `subnet_id` and `security_group_id` in the variables further down the in same file.

**Comment by mcapuccini** [comment]
@pditommaso it is now possible: #169. Please give a look at the network configuration: http://kubenow.readthedocs.io/en/latest/getting_started/bootstrap.html#bootstrap-on-amazon-web-services-ec2
