### ISSUE TITLE
Helm need to be installed by default user

### ISSUE THREAD

**Issue by andersla** [kubenow/KubeNow#103]
currently helm repositories are ending up in /root/.helm/repository/repositories.yaml and not found by default user ubuntu

**Comment by carmat88** [comment]
In [`requirement.sh`](https://github.com/kubenow/KubeNow/blob/master/packer/requirements.sh), line 58, we are moving the helm binary via `sudo to /usr/local/bin `.

**Possible Fix**: Adding one extra line after line 58 with the following command:

`chown ubuntu:ubuntu /usr/local/bin/helm`

**When**: This fix will be done once creation of KubeNow images will be finally decoupled.

**Comment by andersla** [comment]
I actually don't think that is the problem. It is in the playbook doing a helm-init. This executed as root - but have changed the playbook for v0.3

**Comment by carmat88** [comment]
@andersla Aha, thanks! As per our discussion, in the [`main.yml`](https://github.com/kubenow/KubeNow/blob/master/playbooks/roles/start-helm/tasks/main.yml) file for the Helm's playbook at line 3: `become: yes` is triggering the superuser mode.

**Fix**: removing line 3 does fix the issue. No need to modify [`requirement.sh`](https://github.com/kubenow/KubeNow/blob/master/packer/requirements.sh)

@mcapuccini : just FYI, Anders found the culprit.
