### ISSUE TITLE
Prerequisites security check while bootstrapping on OpenStack

### ISSUE THREAD

**Issue by carmat88** [kubenow/KubeNow#105]
In case users forget to source the OpenStack RC file for their tenancy, then importing the KubeNow image (only the first time you are deploying) will fail and return the following error:

**`fatal: [localhost]: FAILED! => {"attempts": 3, "changed": true, "cmd": "glance image-show  | grep -w status | awk '{print $4}'", "delta": "0:00:00.631334", "end": "2017-03-09 12:23:17.306059", "failed": true, "rc": 0, "start": "2017-03-09 12:23:16.674725", "stderr": "usage: glance image-show [--human-readable] [--max-column-width <integer>]\n                         <IMAGE_ID>\nglance image-show: error: too few arguments", "stdout": "", "stdout_lines": [], "warnings": []`**

Since the image is not imported (uploaded in the OpenStack instance), then the related ID is not returned, hence passed to the command `glance image-show`.

**ACTION**: Modify the ansible playbook script ("_import-openstack-image.yml_") by adding some security checks for prerequisites

**Comment by andersla** [comment]
fixed by #129

**Comment by mcapuccini** [comment]
@andersla please wait for PR to be merged before closing
