### ISSUE TITLE
Improving Documentation: Touching upon the nova command while editing terraform script for Kubernetes bootstrap

### ISSUE THREAD

**Issue by carmat88** [kubenow/KubeNow#112]
In the [Kubenow guidelines](http://kubenow.readthedocs.io/en/latest/getting_started/bootstrap.html#bootstrap-on-openstack), It might be worthy to give users some extra tip and info on how to get the external_network_uuid or the list of all currently configured _flavor_ when it comes to modify the `terraform.tfvars` file

**HINT:**
- nova network-list (to get external uuid)
- nova flavor-list

**Comment by andersla** [comment]
Great!
