### ISSUE TITLE
Image import is not tested

### ISSUE THREAD

**Issue by mcapuccini** [kubenow/KubeNow#114]
We need to write CI for image import/export for the supported cloud providers

**Comment by sneumann** [comment]
Hi, image import may not be available on all Ostacks. I get:
```
TASK [upload image kubenow-v020a1 if not present ( url= https://httpd.pharmb.io/kubenow-img/kubenow-v020a1.qcow2 )] ***
changed: [localhost] => {"changed": true, "cmd": "glance --os-image-api-version 1 image-create --copy-from \"https://httpd.pharmb.io/kubenow-img/kubenow-v020a1.qcow2\" --disk-format qcow2 --min-disk 20 --container-format bare --name kubenow-v020a1 --progress | grep -w id | awk '{print $4}'", "delta": "0:00:01.598477", "end": "2017-04-29 20:51:12.423866", "rc": 0, "start": "2017-04-29 20:51:10.825389", "stderr": "400 Bad Request: External sources are not supported: 'https://httpd.pharmb.io/kubenow-img/kubenow-v020a1.qcow2' (HTTP 400)", "stdout": "", "stdout_lines": [], "warnings": []}
```

**Comment by mcapuccini** [comment]
Hi @sneumann. Do you mean that you would like the CI to import the image automatically in your OpenStack installation?

**Comment by mcapuccini** [comment]
Fixed in #158

**Comment by sneumann** [comment]
Hi, sorry for the late response, my issue is that on an OStack without 
support for remote image locations there is the response `400 Bad Request: External sources are not supported` but the ansible snippet will happily retry until it bails out. 
It should be smart and give a reasonable error message for thus 400 Bad request.
Yours, Steffen

**Comment by mcapuccini** [comment]
I see! I just merged a major refactory #158 that also fixed some problems with the OpenStack import. Would you mind to test it?

**Comment by sneumann** [comment]
Is there a point if the os does not support pointing to an http location
And insists on a real file upload?
Yours Steffen

---
I blame Android for the brevity and typos

**Comment by mcapuccini** [comment]
@sneumann Yes, there is a point, the new playbook downloads locally first and then uploads to OS. In the new glance API they removed the http/https image location when uploading images. I don't understand why they've done this. I was doing some research on Google, but I didn't really find any explanation for that. We'll do more research and come back to you.
