### ISSUE TITLE
Create separated repository for documentation

### ISSUE THREAD

**Issue by mcapuccini** [kubenow/KubeNow#118]
We need a separated repo for the documentation. This will allow for easier separation between documentation tests and infrastructure tests.

**Comment by carmat88** [comment]
To Do:

1. - Create a separate repo
2. - Verify if possible to kept previous contributions (history) and tags
3. - Apply syntax and Sphinx checks:
       - https://github.com/atom/spell-check
       - http://www.sphinx-doc.org/en/stable/

**Comment by mcapuccini** [comment]
We may get some inspiration from this: https://github.com/spotify/luigi/blob/f062ea2aae6a41985986c376736a83abfa0b3ef5/tox.ini#L109

**Comment by carmat88** [comment]
Bullet points 1 and 2 are done: https://github.com/kubenow/docs

Looking at n° 3

**Comment by carmat88** [comment]
Separate repo for documentation has been created as per above requirements.
