### ISSUE TITLE
[OpenStack] Issues with Glance

### ISSUE THREAD

**Issue by jonandernovella** [kubenow/KubeNow#123]
When deploying the latest KubeNow image on the cloud, I get the following error: 

`fatal: [localhost]: FAILED! => {"attempts": 10, "changed": true, "cmd": "sudo glance image-show  | grep -w status | awk '{print $4}'", "delta": "0:00:00.337123", "end": "2017-03-20 17:50:44.264406", "failed": true, "rc": 0, "start": "2017-03-20 17:50:43.927283", "stderr": "usage: glance image-show [--human-readable] [--max-column-width <integer>]\n                         <IMAGE_ID>\nglance image-show: error: too few arguments", "stdout": "", "stdout_lines": [], "warnings": ["Consider using 'become', 'become_method', and 'become_user' rather than running sudo"]} OpenStack`

It seems that glance requires more arguments than what is provided. Below, the current flawed code:

`sudo glance image-show {{ image_id }} | grep -w status | awk '{print $4}'`

**Comment by andersla** [comment]
I think this also is resolved by #129
Please reopen if not

**Comment by mcapuccini** [comment]
@andersla please wait for PR to be merged before closing
