### ISSUE TITLE
Verify If less packages can be used for creating Documentation with Sphinx (readocs) 

### ISSUE THREAD

**Issue by carmat88** [kubenow/KubeNow#124]
Currently in our [documentation guidelines](https://github.com/kubenow/docs) it is being required to install three packages about Sphinx:

1. sphinx (this should stay mandatory)
2. sphinx-autobuild (optional, mainly for testing locally)
3. sphinx_rtd_theme (maybe mandatory for rendering purposes with readocs)

TO DO:

- testing by installing either 1 or 2 packages

**Comment by mcapuccini** [comment]
@carmat88 is this resolved?

**Comment by carmat88** [comment]
@mcapuccini I've done some tests and can confirm what described above.

1. _**Sphinx**_ is mandatory in order to build the documentation via the Makefile

2. _**sphinx-autobuild**_ cannot of corse run if the former is uninstalled. This binary is needed only for an interactive creation of the doc, i.e. to dynamically build it as changes are made. Very useful, but not essential in the sense that a make command (e.g `make html`) will successfully run anyway;

3. _**sphinx_rtd_theme**_ is necessary, cannot be uninstall. Without it, errors and exception are being thrown by both the previous commands.;

4. Last but not least, it is not needed to install the aforementioned packages via _**sudo**_

**CONCLUSION:** We could conclude that only n° 1 and 3 are really needed as prerequisites to build the documentation. _Sphinx-autobuild_ is cool and handy, but just an extra. What we could do is to maybe clarify the latter but at the same time leave it as info for users interested in the KubeNow project (a well documented project will likely bring satisfaction in playing around with it, above all if in the process they could learn extras, such as using sphinx-autobuild).

Let me know how we would like to proceed and if you would like me to draft some minor revisions.

**Comment by mcapuccini** [comment]
Thanks @carmat88! I think we can leave sphinx-autobuild in the instructions, but I think it may be good to remove sudo.

**Comment by carmat88** [comment]
@mcapuccini Sudo has been removed as requested. See PR here: https://github.com/kubenow/docs/pull/5
