### ISSUE TITLE
K8s not successfully started when using too few nodes/small flavor size

### ISSUE THREAD

**Issue by StaffanArvidsson** [kubenow/KubeNow#126]
Running on OpenStack (SSC) using:
master_flavor = ssc.small
node_count = "2"
node_flavor = "ssc.medium"
edge_count = "1"
edge_flavor = "ssc.medium"

running: 
> terraform apply openstack

finishes successfully, but running the following command to show that everything worked says that many of the kubernetes pods are not running due to STATUS "Outofcpu":

> ansible master -a 'kubectl get pods --show-all --all-namespaces'

We tried bumping flavor size and node_count/edge_count but that results in the same "OutOfcpu" STATUS for many pods.

**Comment by mcapuccini** [comment]
@jonandernovella did you experience the same on SSC?

**Comment by jonandernovella** [comment]
@mcapuccini @StaffanArvidsson I did not experience this. Please come by tomorrow if you continue experiencing this issue.

**Comment by jonalv** [comment]
Running with three medium nodes now (one master, one edge and one node), the kubedns pod get's stuck at ContainerCreating (0/4). The logs for the pod looks like 
[log.txt](https://github.com/kubenow/KubeNow/files/860795/log.txt)

**Comment by mcapuccini** [comment]
@jonalv is this before or after running `ansible-playbook playbooks/install-core.yml`?

**Comment by jonalv** [comment]
This was before. Will try to run that stuff as well now

**Comment by jonalv** [comment]
It seems medium sized nodes are needed. As for the getting stuck part that doesn't happen once the core stuff is installed. I suggest this ticket can be closed.
