### ISSUE TITLE
Running GlusterFS on dedicated nodes instead of installing on all the nodes

### ISSUE THREAD

**Issue by carmat88** [kubenow/KubeNow#127]
Currently once the infrastructure has been spun up and the Phenomenal application is deployed, some performance issues are being encountered when trying to run the preprocessing analysis of the entire dataset, precisely during the _FeatureLinker_ task.

It has been noticed a very high network overhead among the nodes (as consequence access the dataset due to GlusterFS being spread across them), which leads to an increasing number of timeouts while trying to fetch such files making the edge node/s crashing first followed by the other nodes in a domino's effect fashion.

As per discussion with @mcapuccini , it might be necessary to add some dedicated nodes for taking care of running GlusterFS.

**Comment by mcapuccini** [comment]
Fixed in #221
