### ISSUE TITLE
Need to fix kubernetes version when running kubeadm init

### ISSUE THREAD

**Issue by andersla** [kubenow/KubeNow#135]
kubeadm is by default pulling latest version of kubernetes and this should instead be fixed to a specific version that we have tested and is working well. This can be done with kubeadm init --kubernetes-version as described here https://kubernetes.io/docs/admin/kubeadm/

**Comment by mcapuccini** [comment]
We merge a dirty fix, but this is still to be considered open. We need to add fix the packer build before closing this.
