### ISSUE TITLE
deployment fails if a non standard terraform.tfvars file is being used

### ISSUE THREAD

**Issue by andersla** [kubenow/KubeNow#142]
If user is specifying an own terraform.tfvars file then playbook https://github.com/kubenow/KubeNow/blob/master/playbooks/roles/common/tasks/wait-nodes.yml fails because play - name: "render node count" is relying on terraform.tfvars when calculating number of nodes to wait for

**Comment by mcapuccini** [comment]
@andersla you mean when you specify it with `-var-file`?

**Comment by andersla** [comment]
yes, workaround is to specify "nodes_count=xx" when running ansible playbook, e.g. `ansible-playbook -e "nodes_count=3" --skip-tags "glusterfs" playbooks/install-core.yml`

**Comment by mcapuccini** [comment]
nice! I'll fix this when I'll refactor the terraform deployment 🙂

**Comment by mcapuccini** [comment]
Fixed in #160. @andersla please reopen if I am wrong.
