### ISSUE TITLE
openstack_compute_instance_v2.master: Error waiting for instance XXX to become ready: unexpected state 'ERROR', wanted target 'ACTIVE'. last error: %!s(<nil>)

### ISSUE THREAD

**Issue by PayamEmami** [kubenow/KubeNow#143]
Hello,

I get this error when i want to deploy on openstack:
openstack_compute_instance_v2.master: Error waiting for instance (a34baefe-a2a6-49f6-bf0b-214a3151d3dd) to become ready: unexpected state 'ERROR', wanted target 'ACTIVE'. last error: %!s(<nil>)

In the instance message it says:
Exceeded maximum number of retries. Exceeded max scheduling attempts 5 for instance 43d47d19-1ed3-4c47-ad42-100a0ea23dc7. Last exception: [Errno 2] No such file or directory

By the way, i could get it up and running yesterday!
Best,
Payam

**Comment by andersla** [comment]
It looks like an internal error with the OpenStack installation, what cloud are you using?

**Comment by mcapuccini** [comment]
Hi @PayamEmami! Just to make sure that it is not a problem with terraform, could you please try to start a VM instance manually from the OpenStack interface? If it fails then please contact OpenStack support.

**Comment by andersla** [comment]
Could also maybe be some problem with the terraform.tfstate, you might need to delete the terraform.tfstate and the .terraform directory in your KubeNow directory.
Before you do that make sure to do a `terraform destroy openstack`

**Comment by mcapuccini** [comment]
From Slack:

Payam Emami [4:41 PM] 
now i'm getting this to start an instance from openstack web. block device mapping is invalid . any how let's leave it for now. Just wanted to try a workflow no that important. let's keep in touch. thank you

It is a problem with SNIC OpenStack, closing for now
