### ISSUE TITLE
Troubleshoot section seems to not have been updated

### ISSUE THREAD

**Issue by carmat88** [kubenow/KubeNow#151]
In the [troubleshooting section for Openstack](https://kubenow.readthedocs.io/en/latest/troubleshoot/trouble-os.html) a paragraph is missing even though is present in the docs repo: https://github.com/kubenow/docs/blob/master/troubleshoot/trouble-os.rst

Here was the related PR: https://github.com/kubenow/docs/pull/5/files

The test of clearing the cache or opening with a different browser was not successful.

**Comment by mcapuccini** [comment]
It's now fixed. It was a problem with a webhook.
