### ISSUE TITLE
Security upgrade on images

### ISSUE THREAD

**Issue by andersla** [kubenow/KubeNow#155]
We could run "sudo unattended-upgrades -d" (installs security updates only) in bootstrap script to make sure nodes gets latest security updates.

**Comment by mcapuccini** [comment]
I think this is included in `sudo apt-get update`, don't we already run this? I think we need to have a playbook to run the security updated while a cluster is running as well.

**Comment by andersla** [comment]
We only run it at build process - not when image is a few weeks old. I think a playbook or maybe a scheduled task in kubernetes is a good option?

**Comment by andersla** [comment]
https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/

**Comment by mcapuccini** [comment]
Oh yes, that looks good!

**Comment by mcapuccini** [comment]
Closing in favour of #265
