### ISSUE TITLE
Linux extra no longer needed in requirements

### ISSUE THREAD

**Issue by andersla** [kubenow/KubeNow#157]
from Xenial linux v. 4.4.0-75.96 aufs.ko is included in linux kernel package, which means linux kernel extras is no longer needed. see: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1673498
On amazon installing linux-kernel-extras is causing following error currently: `amazon-ebs: E: Unable to locate package linux-image-extra-4.4.0-1013-aws`

**Comment by mcapuccini** [comment]
Good to know. Maybe @carmat88 spotted this too.

**Comment by carmat88** [comment]
@andersla @mcapuccini Thanks guys, though did not experience any issue while building on amazon. However if it is unnecessary anymore, then we can slim down the requirement script. Will do some tests by first commenting those lines and then removing them if tests were successful.

**Comment by carmat88** [comment]
@andersla @mcapuccini I can confirm that the Linux extra packages seem to no longer be needed as per new image building process in https://github.com/kubenow/image
