### ISSUE TITLE
Decouple storage available in gluster from flavour

### ISSUE THREAD

**Issue by sneumann** [kubenow/KubeNow#159]
Hi, currently the gluster storage is living in the root disk of the individual nodes. 

If I need more shared space for metabolomics data, I need to artificially select very large flavours, and unnecessarily exceed e.g. my RAM quota.

The filesystem behind the gluster nodes should be on its own ephemeral disk or volume.
@pcm32 had a prototype for that at some stage.  Yours, Steffen

**Comment by mcapuccini** [comment]
Good point! @andersla has already implemented this in a dev branch, I am in the process o merging that and some other improvements.

**Comment by mcapuccini** [comment]
Fixed in #221
