### ISSUE TITLE
PR template update

### ISSUE THREAD

**Issue by mcapuccini** [kubenow/KubeNow#186]
The PR template needs to be updated on the image repository and the docs repository.

**Comment by mcapuccini** [comment]
It probably good to have the guidelines as a separated document, and to have a simpler template.

**Comment by carmat88** [comment]
@mcapuccini Is this still something to take care of? If I am not wrong you introduced a PR template in all the above mentioned repos, isn't it? Cheers

**Comment by mcapuccini** [comment]
@carmat88 yep, but we decided to have a documentation page with the contribution guidelines, can you take care of that? Once this is done we can trim down the PR template, and have it in every repo.

**Comment by carmat88** [comment]
Sure thing, maybe we could brainstorm anyway so that I have a better overview of how we would like this documentation page to be.
