### ISSUE TITLE
Improving image creation with branches option + Periodic script for cleaning old/test versions

### ISSUE THREAD

**Issue by carmat88** [kubenow/KubeNow#202]
Currently the building process creates either a release or a current KubeNow image based on whether we are on the master or a branch respectively. However when being in any testing branches only the `kubenow-current` is built and **will overwrite any previous ones in both GCE and AWS** each time.

It could be useful to use something like `TRAVIS_TAG` variable to check if we are in a tag or in the master, and `TRAVIS_BRANCH` to get the tag name.

This possible solution requires though a periodic script that will clean once in a while all the various created `TRAVIS_TAG/TRAVIS_BRANCH` images. This is particular needed as we are copying AMIs across all our regions in AWS, hence we can easily end up with many currents and testing AMIs.

**Comment by mcapuccini** [comment]
@carmat88 this can be closed after we merged https://github.com/kubenow/image/issues/9 right?

**Comment by mcapuccini** [comment]
Just realized that we need the cron job before closing this.

**Comment by carmat88** [comment]
@mcapuccini That's right. I'm already working on it ;-)

**Comment by carmat88** [comment]
This has been addressed by now. Cheers!
