### ISSUE TITLE
Need to update docs

### ISSUE THREAD

**Issue by mcapuccini** [kubenow/KubeNow#203]
We need to update docs after merging #201 #183 #185. The getting started can be drastically simplified now, and we can add the cloudflare/edge part as advanced topic.

**Comment by mcapuccini** [comment]
We need to document also the Gluster storage on dedicated nodes

**Comment by mcapuccini** [comment]
Most of the documentation has been updated. We need a section "advanced topics" where we explain how to deploy: edge nodes, glusterfs nodes, cloudflare DNS records, proxied Cloudflare services and single node deployments. I am short in time right now, but we can leave this out for 0.3.0. Maybe @carmat88 could take care of this, I guess this is a nice way to dig into more advanced k8s topics. This has not super hight priority, I think that most of those features are for power users, and it is to some extent easy to guess the configuration from the templates.

**Comment by carmat88** [comment]
Sure, always glad to contribute and dig into new topics. Will then ping you in regard of such matter.
