### ISSUE TITLE
Compress openstack qcow image before upload to bucket

### ISSUE THREAD

**Issue by andersla** [kubenow/KubeNow#208]
When compressing image using the command `qemu-img convert -O qcow2 -c kubenow-v030a.qcow2 kubenow-v030a.compressed.qcow2` The size went fron 2.8GB to 997MB!!

**Comment by mcapuccini** [comment]
what is the status of this?

**Comment by andersla** [comment]
Fixed by carmat I am pretty sure

**Comment by carmat88** [comment]
Hey Guys! Indeed, you can see the `-c` option [here](https://github.com/kubenow/image/blob/master/bin/os_tf.sh)
