### ISSUE TITLE
Lookup openstack network-id from network-name with TF data-lookup

### ISSUE THREAD

**Issue by andersla** [kubenow/KubeNow#210]
Lookup openstack network-id from network-name with TF data-lookup

**Comment by mcapuccini** [comment]
What does this mean? 🙂

**Comment by andersla** [comment]
Instead of both network id, openstack users will be able only to provide network-name, network id will be looked up by terraform data provider

**Comment by mcapuccini** [comment]
This is now fixed 🙂
