### ISSUE TITLE
Renaming AWS S3 bucket eu-frankfurt

### ISSUE THREAD

**Issue by carmat88** [kubenow/KubeNow#227]
In order to deploy soon cron-jobs in Travis for taking care of cleaning old kubenow-images, we would need to rename the recently created S3 bucket called "_kubenow-eu-frankfurt_" to "_kubenow-eu-central-1_" if possible. Reasons of this revision lie within the syntax logic of AWS s3 APIs [hence a simpler identification of the bucket with its region's name]

**NOTE:** In aws s3 "renaming" cannot actually be done. We need to create a new one, move everything from the previous and then delete the former.

**Comment by carmat88** [comment]
@andersla Let me know if you have any questions regarding this. In case having a different name will imply too many modifications of other files, then I can figure something different out for the AWS cron-job. Last but not least, let me know if there is anything I can help with.

**Comment by andersla** [comment]
fixed with #231

**Comment by carmat88** [comment]
Fantastic, many thanks!
