### ISSUE TITLE
KubeNow Image import fails on DreamHost's DreamCompute OpenStack platform

### ISSUE THREAD

**Issue by logixworx** [kubenow/KubeNow#230]
(400) Client Error for url: https://iad2.dream.io:9292/v2/images Bad Request

Should it be  https://iad2.dream.io:9292/images   and not https://iad2.dream.io:9292/v2/images?  

Thats what is shown under the API Access tab in the panel
Maybe other URL's need to be updated.
Here is DreamCompute's API Access tab (I removed the ids and replaced with (id)):
Compute | https://iad2.dream.io:8774/v2/(id)
Identity | https://iad2.dream.io:5000/v2.0
Image | https://iad2.dream.io:9292
Network | https://iad2.dream.io:9696
Volume | https://iad2.dream.io:8776/v1/(id)
Volumev2 | https://iad2.dream.io:8776/v2/(id)

ubuntu@kubenow:~/KubeNow$ ansible-playbook playbooks/import-openstack-image.yml --limit @/home/ubuntu/KubeNow/playbooks/import-openstack-image.retry
 [WARNING]: Host file not found: inventory

 [WARNING]: provided hosts list is empty, only localhost is available

PLAY [localhost] ***********************************************************************************

TASK [set image facts] *****************************************************************************
ok: [localhost]

TASK [check if image is present in OpenStack] ******************************************************
ok: [localhost]

TASK [download KubeNow image] **********************************************************************
changed: [localhost]

TASK [wait for image download to be done] **********************************************************
FAILED - RETRYING: wait for image download to be done (30 retries left).
FAILED - RETRYING: wait for image download to be done (29 retries left).
 [WARNING]: Consider using get_url or uri module rather than running curl

changed: [localhost]

TASK [upload image to OpenStack] *******************************************************************
changed: [localhost]

TASK [wait for image upload to be done] ************************************************************
FAILED - RETRYING: wait for image upload to be done (30 retries left).
fatal: [localhost]: FAILED! => {"ansible_job_id": "822167518781.10297", "attempts": 2, "changed": false, "extra_data": null, "failed": true, "finished": 1, "msg": "(400) Client Error for url: https://iad2.dream.io:9292/v2/images Bad Request (Inner Exception: Extra data: line 1 column 5 - line 5 column 4 (char 4 - 331))"}

RUNNING HANDLER [delete local image] ***************************************************************
        to retry, use: --limit @/home/ubuntu/KubeNow/playbooks/import-openstack-image.retry

PLAY RECAP *****************************************************************************************
localhost                  : ok=5    changed=3    unreachable=0    failed=1

**Comment by mcapuccini** [comment]
Hi @logixworx! Thanks for opening this issue.  

What version of ansible are you using?

Would you mind to upgrade the python requirements, and rety? You can do it by running this command:

```
sudo pip install --upgrade dnspython jmespath apache-libcloud shade
```

**Comment by logixworx** [comment]
same error.

ansible --version
ansible 2.3.1.0

all the versions are the same as listed in your pip install.  I dont have $SHADE_VERSION set in my env but pip list shows    shade (1.23.0).   Should $SHADE_VERSION be set?

**Comment by mcapuccini** [comment]
Sorry, I forgot to replace that one hehe. We run the CI with shade version `1.21.0`. If you get the same error try to install the latest `pip install --upgrade shade`. We rely on shade for the image upload. Please let me know how it goes.

**Comment by logixworx** [comment]
i do have the latest installed (shade 1.23) .  You said the CI is version 1.21  Wouldnt the CI need to be updated?

**Comment by mcapuccini** [comment]
@logixworx trying it right now https://travis-ci.org/kubenow/KubeNow/builds/275904555

**Comment by mcapuccini** [comment]
The test with shade 1.23 passed, so I assume there is some other issue. We test only on a few OpenStack providers, and the CI is tests on [CityCloud](https://www.citycloud.com) only.

However, now that I am reading better your first message I am thinking of another possible cause for your issue. I suspect that `OS_AUTH_URL` is set to `https://iad2.dream.io:9292` instead of `https://iad2.dream.io:9292/v2` in your environment. Can you try to run `export OS_AUTH_URL=https://iad2.dream.io:9292/v2`, and then try again?

**Comment by logixworx** [comment]
ubuntu@kubenow:~/KubeNow$ export OS_AUTH_URL=https://iad2.dream.io:9292/v2
ubuntu@kubenow:~/KubeNow$ ansible-playbook playbooks/import-openstack-image.yml
 [WARNING]: Host file not found: inventory

 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***********************************************************************************

TASK [set image facts] *****************************************************************************
ok: [localhost]

TASK [check if image is present in OpenStack] ******************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "No handlers could be found for logger \"keystoneauth.identity.generic.base\"\nTraceback (most recent call last):\n  File \"/tmp/ansible_dMTRyO/ansible_module_os_image_facts.py\", line 169, in <module>\n    main()\n  File \"/tmp/ansible_dMTRyO/ansible_module_os_image_facts.py\", line 158, in main\n    image = cloud.get_image(module.params['image'])\n  File \"/home/ubuntu/.local/lib/python2.7/site-packages/shade/openstackcloud.py\", line 3074, in get_image\n    return _utils._get_entity(self.search_images, name_or_id, filters)\n  File \"/home/ubuntu/.local/lib/python2.7/site-packages/shade/_utils.py\", line 220, in _get_entity\n    entities = func(name_or_id, filters, **kwargs)\n  File \"/home/ubuntu/.local/lib/python2.7/site-packages/shade/openstackcloud.py\", line 1550, in search_images\n    images = self.list_images()\n  File \"/home/ubuntu/.local/lib/python2.7/site-packages/shade/openstackcloud.py\", line 2130, in list_images\n    if self._is_client_version('image', 2):\n  File \"/home/ubuntu/.local/lib/python2.7/site-packages/shade/openstackcloud.py\", line 457, in _is_client_version\n    client = getattr(self, client_name)\n  File \"/home/ubuntu/.local/lib/python2.7/site-packages/shade/openstackcloud.py\", line 525, in _image_client\n    'image', min_version=1, max_version='2.latest')\n  File \"/home/ubuntu/.local/lib/python2.7/site-packages/shade/openstackcloud.py\", line 404, in _get_versioned_client\n    if adapter.get_endpoint():\n  File \"/home/ubuntu/.local/lib/python2.7/site-packages/keystoneauth1/adapter.py\", line 223, in get_endpoint\n    return self.session.get_endpoint(auth or self.auth, **kwargs)\n  File \"/home/ubuntu/.local/lib/python2.7/site-packages/keystoneauth1/session.py\", line 942, in get_endpoint\n    return auth.get_endpoint(self, **kwargs)\n  File \"/home/ubuntu/.local/lib/python2.7/site-packages/keystoneauth1/identity/base.py\", line 380, in get_endpoint\n    allow_version_hack=allow_version_hack, **kwargs)\n  File \"/home/ubuntu/.local/lib/python2.7/site-packages/keystoneauth1/identity/base.py\", line 271, in get_endpoint_data\n    service_catalog = self.get_access(session).service_catalog\n  File \"/home/ubuntu/.local/lib/python2.7/site-packages/keystoneauth1/identity/base.py\", line 135, in get_access\n    self.auth_ref = self.get_auth_ref(session)\n  File \"/home/ubuntu/.local/lib/python2.7/site-packages/keystoneauth1/identity/generic/base.py\", line 196, in get_auth_ref\n    self._plugin = self._do_create_plugin(session)\n  File \"/home/ubuntu/.local/lib/python2.7/site-packages/keystoneauth1/identity/generic/base.py\", line 191, in _do_create_plugin\n    raise exceptions.DiscoveryFailure('Could not determine a suitable URL '\nkeystoneauth1.exceptions.discovery.DiscoveryFailure: Could not determine a suitable URL for the plugin\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
        to retry, use: --limit @/home/ubuntu/KubeNow/playbooks/import-openstack-image.retry

PLAY RECAP *****************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1

**Comment by mcapuccini** [comment]
Alirght... Does DreamHost support Keystone v3? The version that you are using right now (v2) is deprecated https://developer.openstack.org/api-ref/identity/v2/index.html.

**Comment by logixworx** [comment]
https://iad2.dream.io:9292    shows:

{"versions": [{"status": "CURRENT", "id": "v2.4", "links": [{"href": "http://iad2.dream.io:9292/v2/", "rel": "self"}]}, {"status": "SUPPORTED", "id": "v2.3", "links": [{"href": "http://iad2.dream.io:9292/v2/", "rel": "self"}]}, {"status": "SUPPORTED", "id": "v2.2", "links": [{"href": "http://iad2.dream.io:9292/v2/", "rel": "self"}]}, {"status": "SUPPORTED", "id": "v2.1", "links": [{"href": "http://iad2.dream.io:9292/v2/", "rel": "self"}]}, {"status": "SUPPORTED", "id": "v2.0", "links": [{"href": "http://iad2.dream.io:9292/v2/", "rel": "self"}]}, {"status": "DEPRECATED", "id": "v1.1", "links": [{"href": "http://iad2.dream.io:9292/v1/", "rel": "self"}]}, {"status": "DEPRECATED", "id": "v1.0", "links": [{"href": "http://iad2.dream.io:9292/v1/", "rel": "self"}]}]}

**Comment by logixworx** [comment]
check this out... might clue us in as to what's wrong with DreamCompute

https://adam.younglogic.com/2016/07/bypassing-discovery-keystoneauth1/

**Comment by mcapuccini** [comment]
@logixworx then let's try to set `export OS_AUTH_TYPE=v3password`, maybe shade will recognize the setting 🙂

**Comment by logixworx** [comment]
didnt work, but I eventually figured that link is actually outdated & the issue no longer exists.  DreamHost is set up for v3 

Let's go back..  so the error says:  

"(400) Client Error for url: https://iad2.dream.io:9292/v2/images Bad Request (Inner Exception: Extra data: line 1 column 5 - line 5 column 4 (char 4 - 331))"}

if https://iad2.dream.io:9292/v2/images is a valid url, what is it supposed to request/return?

**Comment by mcapuccini** [comment]
Alright! Please try to run `openstack image list`, so we can check if it works with the standard openstack client (https://docs.openstack.org/glance/latest/admin/manage-images.html).

**Comment by logixworx** [comment]
$ openstack image list
+--------------------------------------+---------------+-------------+
| ID                                   | Name          | Status      |
+--------------------------------------+---------------+-------------+
| afa49adf-2831-4a00-9c57-afe1624d5557 | CentOS-6      | active      |
| d83cc53a-720a-4972-8d9a-f92299571920 | CentOS-7      | deactivated |
| f84868a5-5261-404a-9c54-ec317ea16b94 | CentOS-7      | active      |
| a93aa9fa-b6b5-4fe3-8e53-1373612628f5 | CoreOS        | active      |
| b67b74bc-c3a8-4087-9c28-de02161fdedd | CoreOS        | deactivated |
| 5cb9c233-5867-4e47-80a1-9d774f800444 | Debian-7      | active      |
| 8eac618e-ee9b-459d-92d4-b6a49e94b207 | Debian-8      | active      |
| b105ad3b-7df8-4318-9c3d-4e4fa4cc4563 | Debian-8      | deactivated |
| 713f2fbc-05c5-491b-9e02-e000861e7b30 | Fedora-24     | active      |
| b4516e23-2358-4400-9396-32e223eceb01 | Fedora-25     | active      |
| df0e0cd9-f8b2-4e1c-8f59-70bf84692ae9 | RancherOS     | active      |
| 842c207f-6964-4ed7-a41a-06ec66a7c954 | Ubuntu-14.04  | active      |
| 23f77038-51dc-40f3-8714-50612b0efb24 | Ubuntu-16.04  | active      |
| 3e5e8264-1e0e-418a-a76b-111e9d9bfad0 | rancheros-iso | active      |
+--------------------------------------+---------------+-------------+

**Comment by mcapuccini** [comment]
@andersla could you point @logixworx to your bash image import that uses the openstack CLI? I think that using your script he would be able to import the image.

**Comment by andersla** [comment]
Hi @logixworx 
You could try uploading image with script bin/image-upload-openstack.sh
It is on branch feature/os-imageuploadscript 
`git checkout feature/os-imageuploadscript `
It requires OpenStack python glance client: `pip install python-glanceclient`
As before, first source your credentials file, then run
`bin/image-upload-openstack.sh`
/Anders

**Comment by logixworx** [comment]
The image upload script worked, though it initially errored because DreamCompute doesn't generte qcows images and I had to edit it to make a raw image instead.

The bootstrap instructions that come next is either incomplete or outdated. Some command options for nova no longer exist & appear to have been moved to the openstack command? and the terraform instructions seem to be missing some options. I played around with some options but couldn't get past the terraform instructions.

**Comment by logixworx** [comment]
I'm gonna work with terraform on DreamCompute independently of KubeNow and see if I can figure out whats different.

**Comment by mcapuccini** [comment]
@logixworx yep, the documentation might be outdated, we are working on that... I'm going to ping you as soon as I'll be done with the new documentation. Thanks a lot for testing with DreamCompute, and please let us know if you manage to find where the problem is.
