### ISSUE TITLE
Gluster/Heketi shouldn't be deployed when there is no glusternode

### ISSUE THREAD

**Issue by mcapuccini** [kubenow/KubeNow#241]
Gluster/Heketi shouldn't be deployed when there is no glusternode. Right now the deploy fails if there is no glusternode up and running, since `install-core.yml` waits for the daemonset to be ready. This is a blocking issue.

 @andersla is there any way to achieve this? You can reproduce the error if you follow the new documentation.

**Comment by mcapuccini** [comment]
@andersla maybe add glusternode_count to the inventory, and skip when it is 0?

**Comment by mcapuccini** [comment]
@andersla probably the same issue it appears when `master_as_edge=false` and `edge_count=0`, we should add this info to the inventory and skip Traefik deploy in that case.

**Comment by andersla** [comment]
And I should also add the optional parameter, gluster_replication_factor. And maybe error if replication_factor and glusternode_count doesn't sum up?

**Comment by mcapuccini** [comment]
No, that should not be necessary, the blocking part doesn't check for any number in particular: https://github.com/kubenow/KubeNow/blob/master/playbooks/roles/heketi-gluster/tasks/gluster-daemonset.yml#L35
