### ISSUE TITLE
Make a stable image release

### ISSUE THREAD

**Issue by mcapuccini** [kubenow/KubeNow#245]
Right now `master` uses a beta image release, before releasing a new stable we need a stable image.

**Comment by carmat88** [comment]
@mcapuccini Shall I proceed and create a stable image since the azure's building process has been included by now?

**Comment by mcapuccini** [comment]
@carmat88 sure! Please go ahead!

**Comment by carmat88** [comment]
@mcapuccini @andersla Stable release is out eventually! Any comments, please let me know. Cheers.

**Comment by andersla** [comment]
Great!
