### ISSUE TITLE
Image documentation needs to be updated after Azure merge

### ISSUE THREAD

**Issue by mcapuccini** [kubenow/KubeNow#258]
We need to add the public URL to the Azure image (if it exists) to this page: http://kubenow.readthedocs.io/en/latest/developers/build-img.html.

**Comment by mcapuccini** [comment]
@andersla is there a public URL where one can download the public image for Azure? Or is it more like Amazon?

**Comment by andersla** [comment]
There is a public URL, but we copy it with the Azurecli so it doesn't need to leave the datacenter

**Comment by andersla** [comment]
Fixed bu KubeNow/docs#18

**Comment by carmat88** [comment]
@andersla Cheers, thanks!

**Comment by carmat88** [comment]
@mcapuccini @andersla Shall I update the following README as well?

- https://github.com/kubenow/image

Otherwise I suppose we could close this issue, isn't it?

**Comment by andersla** [comment]
I guess you could ad it to the README as well, it is nice to show that we are publishing image available to all.

**Comment by carmat88** [comment]
Alright, thanks. It's done ;-) I am gonna close this then. Cheers!
