### ISSUE TITLE
Bash scripts refactory

### ISSUE THREAD

**Issue by mcapuccini** [kubenow/KubeNow#259]
Bash scripts will probably need some refactory soon as we are adding in more and more things into it. One important thing is to put all local variable to lowercase.

**Comment by mcapuccini** [comment]
During refactory we should remove warnings if possible (e.g. https://travis-ci.org/kubenow/KubeNow/jobs/293557859#L2996).

**Comment by mcapuccini** [comment]
After discussion with @andersla we decided to rewrite part of it in GO.

**Comment by mcapuccini** [comment]
@andersla @carmat88 after #311 gets merged I'll be quite happy with the bash scripts. Before we can close this it would be nice if you can take care of the upper case internal variables. It should be done in the cron-job and in the image repo by @carmat88, and in the import scripts by @andersla. Since you have mostly worked to this scripts I think it's going to be faster for you than for me.

@andersla in your image import refactory, please make sure that there is message for the user in each script, so it is clear when the image import script is starting. 

This is not critical, so no hurry! Thanks in advance.

**Comment by carmat88** [comment]
@mcapuccini All good on my end. Only the image repo needed little revision which you can find it [here](https://github.com/kubenow/image/pull/32). Cheers!

**Comment by mcapuccini** [comment]
Thanks everyone!
