### ISSUE TITLE
Adding cleaning script for images created in Azure

### ISSUE THREAD

**Issue by carmat88** [kubenow/KubeNow#263]
Having expanded the list of support cloud provider for KubeNow, we will now need a script to take care cleaning old images built and/or imported/exported in Azure.

**Comment by andersla** [comment]
You can possibly use a modification of:

az storage blob list --account-name kubenow \
                                       --container-name system \
                                       --query [].name \
                                       --output tsv |
                                       grep "/$IMAGE_NAME/.*vhd"

and

az storage blob delete

**Comment by carmat88** [comment]
@andersla Great, thanks a lot for such hint. Will start working at it soon. Cheers

**Comment by andersla** [comment]
I guess you can get even more ideas such as how to log in: https://github.com/kubenow/KubeNow/blob/feature/azure-provider/bin/image-create-azure.sh

**Comment by carmat88** [comment]
@mcapuccini @andersla All good pals, script is in place. Cheers guys!
