### ISSUE TITLE
Install security updates on bootstrap

### ISSUE THREAD

**Issue by mcapuccini** [kubenow/KubeNow#265]
We should install recommended security updates during bootstrap to avoid security issues.

**Comment by carmat88** [comment]
As per our discussion, a first step toward addressing this bullet point has been to install the `unattended-upgrades` package to our default Ubuntu image([here is the related PR](https://github.com/kubenow/image/pull/34)).

Now correct me in case I was wrong, we should still make sure to both include security updates on bootstrap and major Kernel security updates when available. In the latter case, if any is released, then we will directly bake a new kubenow image with such kernel updates and make it a release (or pre-release). Is that correct?

Cheers.
