### ISSUE TITLE
Refactory of building image process - Using Travis Build stage

### ISSUE THREAD

**Issue by carmat88** [kubenow/KubeNow#269]
Currently due to some limitations of the default Travis' VM related to our CI, for Openstack we opted to combine Terraform and Packer by using the concept of post-processors. However this combination leads to an output that is quite cumbersome and tedious to debug ([Terraform's bug](https://github.com/hashicorp/terraform/issues/6468)).

Hence a possible approach would be to use the [Travis' beta feature about build-stages](https://docs.travis-ci.com/user/build-stages) which seems to have been fairly stable so far.

Will Fix: #192

**Comment by carmat88** [comment]
As per our discussion, we may not need to use the build-stages, rather simplifying the Openstack's post-processor by moving that logic into the `after_success` in `.travis.yaml`

**Comment by mcapuccini** [comment]
This should be handled! Please reopen if I am wrong.

**Comment by carmat88** [comment]
That's right. I reckon we could also close #192 . Cheers!
