### ISSUE TITLE
docker file restrictions needs change

### ISSUE THREAD

**Issue by laeeq80** [kubenow/KubeNow#288]
In order to get the provisioning tools we need to run the following command but it has authorization problem

`docker pull kubenow/provisioners:master`

One needs to change mode of a particular docker file as under

`sudo chmod 777 /var/run/docker.sock`

**Comment by mcapuccini** [comment]
@laeeq80 I think that this is a docker error that has not to do with KubeNow. You need to add your user to the Docker group in order to be able to see `/var/run/docker.sock`. Please feel free to reopen if I am wrong.
