### ISSUE TITLE
kn ssh not valid

### ISSUE THREAD

**Issue by laeeq80** [kubenow/KubeNow#290]
"ssh" is not a valid command. I tried

kn ssh

and

kn ssh ubuntu@master

If the above cases are wrong, then better documentation with example is required in http://kubenow.readthedocs.io/en/latest/getting_started/bootstrap.html

**Comment by mcapuccini** [comment]
@laeeq80 thanks for testing. I think we introduced the problem recently, looking at the code it seems like it tests for kn-ssh: https://github.com/kubenow/KubeNow/blob/master/bin/kn#L88

@andersla would you mind to fix it?

**Comment by mcapuccini** [comment]
Fixed #295
