### ISSUE TITLE
Heketi fails to provision volumes with two gluster nodes

### ISSUE THREAD

**Issue by jonandernovella** [kubenow/KubeNow#308]
Using KubeNow version: 0.3.0rc3, Heketi seems to fail to provision volumes with two GlusterFS nodes:

`$ kn kubectl get pvc`
```
main-gs3-pvc   Pending                                      gluster-heketi   7m
meta-gs3-pvc   Pending                                      gluster-heketi   7m
```

`$ kn kubectl describe pvc main-gs3-pvc`

> ProvisioningFailed	Failed to provision volume with StorageClass "gluster-heketi": error [failed to parse "2 "] when parsing value "2 " of option 'volumetype' for volume plugin kubernetes.io/glusterfs

**Comment by mcapuccini** [comment]
@jonandernovella pleas go ahed and try again with 2 glusternodes, and tolerations. This should be in version 0.3.0
