### ISSUE TITLE
Dpkg bug when installing azure-cli

### ISSUE THREAD

**Issue by carmat88** [kubenow/KubeNow#309]
Currently when trying to install the azure-cli packages in our CI an error due to some associated  dpkg packages is returned. This seems to be linked to the following official upstream report: https://bugs.launchpad.net/ubuntu/+source/dpkg/+bug/1730627

Even by updating and/or upgrading dpkg we seem to not be able to solve this glitch for the time being. However this does not concern directly the azure-cli package; though due to the check `set -e` , building in CI will keep failing. As a temporarily workaround we have moved `set -e` like in: 

- https://github.com/kubenow/image/pull/29

and

- https://github.com/kubenow/cron/pull/9

Nevertheless this must be reverted once dpkg bug is solved.

**Comment by andersla** [comment]
Hi @carmat88 I have found that you can install azure cli with pip: `pip install azure-cli`
maybe that could solve your problem

**Comment by carmat88** [comment]
Hi @andersla Ok, will try this alternative although I must admit that on debian machines I don't like installing tools via pip but sometimes it is the only way. Cheers!

**Comment by carmat88** [comment]
@andersla pip seems to not be the most optimal way unfortunately: https://github.com/kubenow/cron/pull/10

**Comment by carmat88** [comment]
All good, glitch has been solved in https://github.com/kubenow/cron/pull/12
