### ISSUE TITLE
Bucket URL is not passed to the environment in the `kn` CLI

### ISSUE THREAD

**Issue by mcapuccini** [kubenow/KubeNow#316]
The variable `IMAGE_BUCKET_URL` should be passed to the environment of the Docker container in the `kn` script. An idea could be to rename all of the KubeNow variables with the prefix `KN_` so that we can pass them with a single line, like we do for `OS_`, `TF_` etc.

**Comment by andersla** [comment]
That sounds great, I have been thinking exactly the same:-)
