### ISSUE TITLE
Upgrade Helm version 

### ISSUE THREAD

**Issue by jonandernovella** [kubenow/KubeNow#319]
Just ran into a problem with our version of Helm: 2.6.1. The issue is explained [here](https://github.com/kubernetes/helm/issues/1707). We'd better upgrade asap.

**Comment by mcapuccini** [comment]
Good that you pointed it out! Could you send a PR? I think it should be in kubenow/image.

**Comment by carmat88** [comment]
Unless I am missing something, from the comments' thread it sounds like developer are noticing and experiencing the same issue with the latest version, 2.7.2. Isn't that the case @jonandernovella ? Cheers.

**Comment by jonandernovella** [comment]
@carmat88 this can be fixed if you allow the value to be an integer for ease-of-use, and then force it to be a string: (t.e: `{{ toString .Values.myfield }}`).

We can close this issue.
