### ISSUE TITLE
Create Helm Chart for Luigi

### ISSUE THREAD

**Issue by carmat88** [kubenow/KubeNow#323]
As per request related to Phenomenal next releases, it seems to be useful to create a Kubenow's chart for luigi using our [container](https://github.com/phnmnl/container-luigi) given that there is no official app in docker hub.

**Comment by mcapuccini** [comment]
Yep, we wanted this for a while. I suggest to start by having it in our repository, and then to move it to the official Kubernets Helm repo.

**Comment by carmat88** [comment]
Hello @mcapuccini  and @andersla . As per our discussion with Marco, the Luigi chart has been first [pushed to the Phnmnl's repo](https://github.com/phnmnl/helm-charts/pull/5).

Later on if need be we could also add it to the Kubenow helm-chart repo. So I guess this can be closed for the time being.

Cheers!

**Comment by carmat88** [comment]
All good, our Luigi helm chart has been merged into [phnmnl/helm-chart](https://github.com/phnmnl/helm-charts) master. Cheers.
