### ISSUE TITLE
kubectl stops working

### ISSUE THREAD

**Issue by jonandernovella** [kubenow/KubeNow#324]
Just hit a similar error to https://github.com/kubernetes/kubeadm/issues/459 on different KubeNow deployments .

It seems that  `kubectl` (on master) stops working once you start a `scp -r . ubuntu@<master-ip>:<master-path>` from your local computer.

A workaround might be upgrading Weave to 2.0.5. However, we are currently using Flannel. So I updated to the latest Flannel version but it is still happening.

**Comment by mcapuccini** [comment]
Hi @jonandernovella. Did you try with a larger master flavor?

**Comment by jonandernovella** [comment]
Quite unfortunately by my side, I was uncounciously copying hidden `kubectl` config files. These were the causes of the problem.

We can close this.
