### ISSUE TITLE
Azure Image copy progress "hangs" at 99.99% for more than 30 minutes

### ISSUE THREAD

**Issue by carmat88** [kubenow/KubeNow#327]
When trying to use different regions for spawning KubeNow clusters in Azure, the `image-create-azure.sh` checks whether the `kubenow` image is available otherwise starts to copy it from the main azure "bucket". However the copy progress reach 99.99% and hangs for more than 30 minutes, resulting in a misleading feedback to the user. Would it actually be possible to show that the copying progress is still pending and not sort of "stuck"?

Cheers!

```
nooneknows@KubeNowAZ$ time kn apply
Using KubeNow version: 0.3.0
Login
CloudName    IsDefault    Name                         State    TenantId
-----------  -----------  ---------------------------  -------  ------------------------------------
AzureCloud   True         Microsoft Azure Sponsorship  Enabled  ac85e4d6-f3c3-46c5-8ef4-3b2a9394969e
Image is not present in this subscription - will create
Create resource-group (if not there already)
Location     Name
-----------  -----------------------------
northeurope  kubenow-images-rg-northeurope
Create storage account (if not there already)
CreationTime                      Kind     Location     Name                      PrimaryLocation    ProvisioningState    ResourceGroup                  StatusOfPrimary
--------------------------------  -------  -----------  ------------------------  -----------------  -------------------  -----------------------------  -----------------
2018-02-08T15:42:59.848486+00:00  Storage  northeurope  kubenow000aed9a78c199829  northeurope        Succeeded            kubenow-images-rg-northeurope  available
Create storage container (if not there already)
Created
---------
False
Get uri of files to copy
Start asynchronous file copy of image def file
Status
--------
pending
Start asynchronous file copy of VHD-file
Status
--------
pending
 / Image copy progress: 99.99%

Done copy image                   
Create image from imported vhd-file
Location    Name          ProvisioningState    ResourceGroup
----------  ------------  -------------------  ------------------------
northeurope      kubenow-v040  Succeeded            kubenow-images-rg-northeurope

Image created

....

real	37m59.823s
user	0m0.164s
sys	0m0.128s
```

**Comment by mcapuccini** [comment]
IMO the situation described in the comment just happened https://github.com/kubenow/KubeNow/blob/master/bin/image-create-azure.sh#L141-L142. It would be good to move the out condition to the top of the loop (and use a while loop instead). Motivation for this can be found here: https://stackoverflow.com/questions/3922599/is-it-a-bad-practice-to-use-break-in-a-for-loop (loop is quite long, and it is hard to understand where it exits). Apart from this, if not too hard, the image size should not be hardcoded, but we should somehow query it at run time before entering the loop. Let me know what you guys think!

**Comment by andersla** [comment]
I think it is all about that when copying the file to a new region - it actually needs to copy 30GB data, and that takes very long time, and when copying within then it is only 3GB.
I have seen this before, will look into it and probably skip that hardcoded image-size condition. I think that when copying within region it takes 5 min and to a new > 30 min (because of size it needs to copy)

**Comment by mcapuccini** [comment]
Then isn't it better to set it to the bigger size? From the user prospective is much better seeing it going very fast from 10-15% to 99%, rather than seeing it stuck on 99%.

**Comment by andersla** [comment]
Yes absolutely:-) But when I did work on it then it always did the last 90% instantly. Then once (or twice I noticed that it took a very long time - but I was too annoyed with Azure for digging into it:-) I guess I'm stuck with it... have to look at it ... buuuhhh

**Comment by andersla** [comment]
If only google and azure could learn from amazon and make users share the public images!

**Comment by mcapuccini** [comment]
Either we get it reliable, or we remove the estimation, it's very confusing for the user otherwise.

**Comment by mcapuccini** [comment]
There is little we can do about it, but I think that having the last 90 instantly is way better than seeing stuck on 99.99% for 30 minutes.

**Comment by mcapuccini** [comment]
oops, closed by mistake 🙂

**Comment by mcapuccini** [comment]
Also we could do it like we do for GCE: https://github.com/kubenow/KubeNow/blob/master/bin/image-create-gce.sh#L58

**Comment by andersla** [comment]
I think thats the way to go - write to the user that sometimes it takes 5 minutes even if the initial estimate is 50 minutes:-)

**Comment by andersla** [comment]
But also I will do another round of investigation of what is the actual cause.

**Comment by mcapuccini** [comment]
> write to the user that sometimes it takes 5 minutes even if the initial estimate is 50 minutes:-)

Not really getting you, but I am happy as long as it doesn't confuse me

**Comment by andersla** [comment]
The initial estimate will always be 30GB = 50 min. But most of the time the last 27GB will be copied in a sec, I don't think we can perdict when.

**Comment by mcapuccini** [comment]
Isn't it better to give an upperbound estimate, rather than an optimistic one?

**Comment by andersla** [comment]
Yes but we say to the users that if they are lucky they only need to wait 5min, then they think - next time I will be lucky even if I have to wait a long time this time:-)

**Comment by mcapuccini** [comment]
Nope, you are not getting me, I am saying that we should estimate 50 minutes, and then maybe if they are lucky with Azure it will take 5. This is my opinion better that saying come back in 5 minute, and then having users wait for 50 minutes (I would assume that the process failed in that case).

**Comment by andersla** [comment]
We will estimate 50 (but mention in parenthisis that it might take much shorter)

**Comment by mcapuccini** [comment]
Yep, that works :-)
