### ISSUE TITLE
Travis CI - Final command `terraform destroy -force "$HOST_CLOUD"` is failing 

### ISSUE THREAD

**Issue by carmat88** [kubenow/KubeNow#339]
As you can see from [this Travis execution](https://travis-ci.org/kubenow/KubeNow/builds/350745723), in all the builds the command `terraform destroy -force "$HOST_CLOUD"` is failing with the following error:

Failed to load root config module: Error loading modules: module keypair: not found, may need to be downloaded using 'terraform get'

This does not affect the final status of the build inasmuch part of the `after_script` build stage, but it does impact on any attempt to re-run same build.

**Comment by mcapuccini** [comment]
@andersla it seems like the `terraform destroy` command needs a `terraform get`... But it is weird since we run `terraform get` in the container, maybe we don't copy `.terraform` directory in the host machine?

**Comment by andersla** [comment]
I think it is because we are using pre-downloaded plugins when we run via provisioner image

**Comment by mcapuccini** [comment]
Any idea on how to fix it? Maybe just run `terraform get`?

**Comment by andersla** [comment]
It might not be enough, maybe terraform init - I will test

**Comment by andersla** [comment]
Not so easy.... it seems like it want the preloaded plugins since thats how terraform-state was created....

**Comment by andersla** [comment]
this did not solve it...
```
terraform get openstack && terraform destroy -force openstack
terraform init openstack && terraform destroy -force openstack
```

**Comment by andersla** [comment]
Solved it, pull request on way:
`travis_retry rm -f .terraform/plugin_path && terraform init "$HOST_CLOUD" && terraform destroy -force -var-file=config.tfvars "$HOST_CLOUD" # in case there is some problem with kn`
