### ISSUE TITLE
Rollback to Travis email notifications

### ISSUE THREAD

**Issue by mcapuccini** [kubenow/KubeNow#358]
A while ago I disabled email notification, and started to push them on Slack instead. However, I find myself forgetting about CI builds and not figuring out for days that a build failed (with some potentially hanging resources). I am thinking to re-enable email notifications for failed builds only. @carmat88 @andersla anything against this?

**Comment by mcapuccini** [comment]
I decided to tune Slack notification instead: https://github.com/kubenow/KubeNow/pull/365, https://github.com/kubenow/image/pull/43.

**Comment by carmat88** [comment]
Hej! I'm fine with both ways if need be. Cheers.

**Comment by mcapuccini** [comment]
I'd like everyone to decide on his own if notifications are needed or not. With Slack you can tune notifications, making it possible. I'll show you guys during next meeting.

**Comment by mcapuccini** [comment]
Never mind... I still don't manage to remember failed builds via slack. Rolling back to mail notifications.
