### ISSUE TITLE
Documentation for Heketi storage class and PVC

### ISSUE THREAD

**Issue by mcapuccini** [kubenow/KubeNow#360]
I have merged @carmat88 advanced topics section in the documentation. I think that it would be nice to expand the GlusterFS section explaining how to claim a GlusterFS volume, explaining that volume provisioning is automatic, as we set it as default storage class.

**Comment by carmat88** [comment]
Howdy again! Quick question: when we say that :

> volume provisioning is automatic

is it equivalent to _"dynamically provisioned"_ as state here: https://kubernetes.io/docs/concepts/storage/dynamic-provisioning/

Cheers.

**Comment by mcapuccini** [comment]
Yep, exactly. Maybe the term `dynamic` is more appropriate.
