### ISSUE TITLE
Test if Azure image gets smaller if smalled disk VM is used by packer

### ISSUE THREAD

**Issue by andersla** [kubenow/KubeNow#361]
Currently we are using a Standard_A1 machine and that one has an internal disk size of 70GB, maybe if we build with a Standard_A1_v2 (10GB internal disk) The raw disk image on Azure gets smaller.

https://docs.microsoft.com/en-us/azure/virtual-machines/windows/sizes

Ultimately It would be great to build our OS image on a 10GB or 5GB machine (smaller raw-image) - but those machines does not exist - could maybe be a request to citycloud.

**Comment by carmat88** [comment]
As per test conducted [here](https://github.com/kubenow/image/pull/41), we could close this issue.
