### ISSUE TITLE
Change chellsceck to Docker image

### ISSUE THREAD

**Issue by andersla** [kubenow/KubeNow#369]
The ubuntu repo-version of shellcheck seem to be broken ( https://travis-ci.org/kubenow/KubeNow/builds/366017980 ), maybe better change to docker image version koalaman/shellcheck

**Comment by mcapuccini** [comment]
Agreed!

**Comment by andersla** [comment]
fixed with #367

**Comment by mcapuccini** [comment]
Merged!
