### ISSUE TITLE
Error when building from Dockerfile

### ISSUE THREAD

**Issue by stephenmoloney** [kubenow/KubeNow#370]
## Description

I have written the PR for the raw disc format over the weekend and now I am trying to test it out but 
when building from docker off master, I am noticing the following error

Steps taken:

```
git clone https://github.com/kubenow/KubeNow.git test_kube && \
cd test_kube && \
docker build --tag test ./
```

- error message
```
Collecting pip
  Downloading pip-10.0.0-py2.py3-none-any.whl (1.3MB)
Installing collected packages: pip
  Found existing installation: pip 8.1.1
    Not uninstalling pip at /usr/lib/python2.7/dist-packages, outside environment /usr
Successfully installed pip-10.0.0
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main
```

- it's breaking on [line 47](https://github.com/kubenow/KubeNow/blob/master/Dockerfile#L47)
- I wonder why others or the travis build is not seeing this.
- I have found one or two solutions . 
- But I am wondering why others aren't seeing this.

**Comment by andersla** [comment]
I get the same error on another branch. It is probably just something that changed in the pip repos the last couple of days.

**Comment by stephenmoloney** [comment]
I made a PR for downloading pip using curl which avoids this problem. Seems that this has happened for others in other projects going back quite some time.
