### ISSUE TITLE
State the Kubernetes version somewhere in the docs

### ISSUE THREAD

**Issue by mcapuccini** [kubenow/KubeNow#375]
Somewhere in the docs we should state the Kubernetes version that we are using.

**Comment by carmat88** [comment]
Howdy! In this document here:

- https://github.com/kubenow/docs/blob/master/getting_started/prerequisites.rst

I am wondering to say something along the line of:

> KubeNow provisioners are distributed via Docker **and based on Kubernetes version 1.9.2-00**

What do you think? Cheers.

**Comment by mcapuccini** [comment]
That'd be great 🙂 (1.9.2, is enough to state)
