### ISSUE TITLE
question about bin/predestroy

### ISSUE THREAD

**Issue by stephenmoloney** [kubenow/KubeNow#393]
Issue:

using docker image: `provisioners/master` and on running `kn destroy` on master, i get the following error:
```
~/kubenow$ kn destroy
/KubeNow_root/bin/kn-destroy: line 7: /KubeNow_root/bin/pre-destroy: No such file or directory
```

I can't find the actual`/KubeNow_root/bin/pre-destroy` script in the source code
```
https://github.com/kubenow/KubeNow/blob/52a5d6e1563e2906ab5d3516801056886e43b686/bin/kn-destroy#L7
```

An ideas what I am doing wrong?

**Comment by andersla** [comment]
This was a piece of testing code that had been merged into master by mistake.
Thanks for reporting @stephenmoloney

**Comment by mcapuccini** [comment]
@andersla reopening, so we can remember to remove it.

**Comment by mcapuccini** [comment]
Just figured out that you are already on top of it 🙂
