### ISSUE TITLE
[question] External load balancer

### ISSUE THREAD

**Issue by stephenmoloney** [kubenow/KubeNow#407]
Hi,

I understand that the docs state that traefik is the load balancer - but I presume this means an internal ingress controller acting as a sort of internal load balancer ?

I'm just wondering if there is an external load balancer?

Read through the source but only found traefik daemonset

https://github.com/kubenow/KubeNow/blob/master/playbooks/roles/traefik/files/traefik-daemonset.yml

**Comment by stephenmoloney** [comment]
I found the answer to this question in the section on edge nodes. http://kubenow.readthedocs.io/en/stable/advanced_topics/edge-nodes.html

**Comment by stephenmoloney** [comment]
To elaborate on my own answer a little bit and make some conclusions as it maybe used to others - feel free to clarify anything here.

There is no external loadbalancer, an 'internal` loadbalancer through traefik is achieved by using the `hostnetwork` and running the `traefik ingress controller` on each node or at least each edge node if using edge nodes.

The key lines to read are:

https://github.com/kubenow/KubeNow/blob/master/playbooks/roles/traefik/files/traefik-daemonset.yml#L3

https://github.com/kubenow/KubeNow/blob/master/playbooks/roles/traefik/files/traefik-daemonset.yml#L17

I suppose that an external loadbalancer is not merited for KubeNow as it's focus is not centered around high availability .

Feel free to correct anything above.

**Comment by mcapuccini** [comment]
Hi @stephenmoloney. I see that you managed to find the answer yourself. 

Just to expand a little bit, we use Traefik instead of an external load balancer, as this service is not provided in some OpenStack installation that we need to support. In the future we may include external load balancer configurations optionally.
