### ISSUE TITLE
Use names instead of IDs in terraform configurations when possible

### ISSUE THREAD

**Issue by mcapuccini** [kubenow/KubeNow#41]
Right now we use quite a lot of UUIDs in terraform configs, it would be good to use names where possible, to simplify the configuration process.

**Comment by andersla** [comment]
The only places I have found UUID in openstack .tfvars is external_net and name is not supported. In packer-conf.json it is in network_id and packer only supports uuid specifying network.

**Comment by mcapuccini** [comment]
closing 😄
